colorscheme default

set current tabstop 4 

hook global WinCreate .* %{ addhl number_lines }
# User added hook
hook global WinCreate .*\.(c|h) %{ 
    hook window InsertChar \t %{ exec -draft -itersel h@ } 
    set formatcmd "indent"
}

map global insert <C-q> <esc>
# Remove trailing spaces.
map global user <C-q>  '%s +(?=\n)<ret>d'
